project:
  type: book

book:
  title: "tapestry notebook"
  author: "Greg Alward"
  date: "9/17/2024"
  chapters:
    - index.qmd
    - part1/intro.qmd
    - presentations/ui_seminar_1.qmd
    - presentations/ui_presentation_1.qmd
    - notebooks/notes.qmd
    - scripts/script_1.qmd
    - data/links_to_data.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



